# Generated by Django 4.1.2 on 2024-09-29 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expect_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('details', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ma-corrective',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('symptom_area', models.CharField(choices=[('AC', 'Air Condition'), ('BRAKE', 'Brake'), ('ELECTRIC', 'Electric'), ('ENGINE', 'Engine'), ('HYDRAULIC', 'Hydraulic'), ('GEARBOX', 'Gearbox'), ('TRANSMISSION', 'Transmission'), ('SPREADER', 'Spreader'), ('OTHER', 'Other')], default='Engine', max_length=20)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('corrective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='maintenance.corrective')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma-symptom',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma-section',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_machine_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma-machine_types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_machines', to='maintenance.machinetype')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_machines', to='maintenance.section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma-machine',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='corrective',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correctives', to='maintenance.machine'),
        ),
        migrations.AddField(
            model_name='corrective',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correctives', to=settings.AUTH_USER_MODEL),
        ),
    ]
