# Generated by Django 4.1.2 on 2024-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='target',
            field=models.FloatField(default=0),
        ),
    ]
