# Generated by Django 4.1.2 on 2024-09-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_machinetype_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='section',
        ),
        migrations.AddField(
            model_name='machine',
            name='terminal',
            field=models.CharField(choices=[('LCMT', 'LCMT'), ('LCB1', 'LCB1')], default='LCMT', max_length=10),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_machine_types', to='maintenance.section'),
        ),
    ]
