# Generated by Django 4.1.2 on 2024-09-29 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0003_remove_machine_section_machine_terminal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('symptom_area', models.CharField(choices=[('AC', 'Air Condition'), ('BRAKE', 'Brake'), ('ELECTRIC', 'Electric'), ('ENGINE', 'Engine'), ('HYDRAULIC', 'Hydraulic'), ('GEARBOX', 'Gearbox'), ('TRANSMISSION', 'Transmission'), ('SPREADER', 'Spreader'), ('OTHER', 'Other')], default='Engine', max_length=20)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
            ],
            options={
                'db_table': 'ma-defect',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expect_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='maintenance.machine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='failures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma-failure',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='corrective',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='user',
        ),
        migrations.DeleteModel(
            name='Corrective',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.AddField(
            model_name='defect',
            name='failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='maintenance.failure'),
        ),
        migrations.AddField(
            model_name='defect',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to=settings.AUTH_USER_MODEL),
        ),
    ]
