# Generated by Django 4.1.2 on 2024-09-30 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0006_alter_defect_details_alter_defect_repair_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='failure',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='machinetype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='failure',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Preventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('details', models.TextField(blank=True, max_length=200, null=True)),
                ('period', models.SmallIntegerField(blank=True, default=500, null=True)),
                ('period_unit', models.CharField(choices=[('HR', 'Hour'), ('KM', 'Kilometer'), ('MOVE', 'Move')], default='HR', max_length=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLAN', 'PLAN'), ('WORKING', 'WORKING'), ('DONE', 'DONE')], default='PLAN', max_length=10)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pms', to='maintenance.machine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma-pm',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
