# Generated by Django 4.1.2 on 2024-09-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_defect_options_alter_failure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure',
            name='category',
            field=models.CharField(choices=[('AO', 'Assit Operation'), ('BO', 'Breakdown outside operation'), ('BD', 'Breakdown'), ('PC', 'Power Cut')], default='BD', max_length=10),
        ),
    ]
