# Generated by Django 4.1.2 on 2024-10-19 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0008_failure_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('details', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='maintenance.machine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma-accident',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(upload_to=maintenance.models.failure_upload_path)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('failure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='maintenance.failure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='failure_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma-failure-image',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(upload_to=maintenance.models.failure_upload_path)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='maintenance.accident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accident_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma-accident-image',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
