# Generated by Django 4.1.2 on 2024-12-19 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0009_accident_failureimage_accidentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentimage',
            name='image',
            field=models.ImageField(upload_to=maintenance.models.accident_upload_path),
        ),
        migrations.AlterField(
            model_name='failure',
            name='category',
            field=models.CharField(choices=[('AO', 'Assit Operation'), ('BO', 'Breakdown outside operation'), ('BD', 'Breakdown'), ('CM', 'Corrective maintenance'), ('PC', 'Power Cut')], default='BD', max_length=10),
        ),
        migrations.CreateModel(
            name='PreventiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(upload_to=maintenance.models.preventive_upload_path)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('preventive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='maintenance.preventive')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preventive_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ma-preventive-image',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
