# Generated by Django 4.1.2 on 2025-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_accident_operation_date_accident_operation_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure',
            name='receiving_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='operation_shift',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night')], default='DAY', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='operation_shift',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night')], default='DAY', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='failure',
            name='operation_shift',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night')], default='DAY', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='operation_shift',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night')], default='DAY', max_length=10, null=True),
        ),
    ]
