# Generated by Django 4.1.2 on 2025-05-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_failure_engine_hour_failure_engine_malfunction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='engine_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preventive',
            name='engine_malfunction',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='preventive',
            name='engine_move',
            field=models.IntegerField(default=0),
        ),
    ]
