# Generated by Django 4.1.2 on 2025-05-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_preventive_engine_hour_preventive_engine_malfunction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='engine_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_hour_next_pm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
