# Generated by Django 4.1.2 on 2026-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_failurecategory_failure_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failurecategory',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]