# Generated by Django 4.1.2 on 2024-03-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='bit_number',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='field_type',
            field=models.CharField(blank=True, choices=[('int', 'int'), ('dint', 'dint'), ('real', 'real'), ('word', 'word'), ('bit', 'bit')], default='int', max_length=10, null=True),
        ),
    ]
