# Generated by Django 4.1.2 on 2022-10-18 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measuring', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_year', models.PositiveSmallIntegerField(default=2022)),
                ('created_month', models.PositiveSmallIntegerField(default=1)),
                ('created_day', models.PositiveSmallIntegerField(default=1)),
                ('created_hour', models.PositiveSmallIntegerField(default=0)),
                ('created_week', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('units', models.CharField(blank=True, max_length=15, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='machine.equipment')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='measuring.parameter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment_item',
                'abstract': False,
            },
        ),
    ]
