# Generated by Django 4.1.2 on 2022-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['seq']},
        ),
        migrations.AddField(
            model_name='item',
            name='seq',
            field=models.IntegerField(default=50),
        ),
    ]
