# Generated by Django 4.1.2 on 2022-10-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_alter_item_options_item_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_value',
            field=models.IntegerField(default=0),
        ),
    ]
