# Generated by Django 4.1.2 on 2024-03-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_datalogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
    ]
